spring:
  application:
    name: homework-project
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration